/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package newpackage;

import java.util.HashSet;

/**
 *
 * @author Emiliano
 */
public class AgregarMateria extends javax.swing.JInternalFrame {
    private HashSet<Materia> materias = new HashSet <>();
    
    /**
     * Creates new form AgregarMateria
     * @param materias
     */
    public AgregarMateria(HashSet<Materia> materias) {
        initComponents();
        this.materias = materias;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpAgregarMateria = new javax.swing.JPanel();
        jlCodigo = new javax.swing.JLabel();
        jlNombre = new javax.swing.JLabel();
        jlAño = new javax.swing.JLabel();
        jlFormulario = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfNombre = new javax.swing.JTextField();
        jtfAño = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbNuevo = new javax.swing.JButton();
        jbsalir = new javax.swing.JButton();

        jlCodigo.setForeground(new java.awt.Color(0, 153, 204));
        jlCodigo.setText("CODIGO DE MATERIA");

        jlNombre.setForeground(new java.awt.Color(0, 153, 204));
        jlNombre.setText("NOMBRE DE LA MATERIA");

        jlAño.setForeground(new java.awt.Color(0, 153, 204));
        jlAño.setText("AÑO AL QUE PERTENECE");

        jlFormulario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlFormulario.setForeground(new java.awt.Color(0, 153, 204));
        jlFormulario.setText("Formulario de Materias");

        jbGuardar.setForeground(new java.awt.Color(0, 0, 0));
        jbGuardar.setText("Guardar ");

        jbNuevo.setForeground(new java.awt.Color(0, 0, 0));
        jbNuevo.setText("Nuevo");

        jbsalir.setForeground(new java.awt.Color(0, 0, 0));
        jbsalir.setText("Salir");
        jbsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpAgregarMateriaLayout = new javax.swing.GroupLayout(jpAgregarMateria);
        jpAgregarMateria.setLayout(jpAgregarMateriaLayout);
        jpAgregarMateriaLayout.setHorizontalGroup(
            jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarMateriaLayout.createSequentialGroup()
                .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpAgregarMateriaLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCodigo)
                            .addComponent(jlNombre)
                            .addComponent(jlAño))
                        .addGap(36, 36, 36)
                        .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtfAño)
                            .addComponent(jtfNombre)
                            .addGroup(jpAgregarMateriaLayout.createSequentialGroup()
                                .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 93, Short.MAX_VALUE))))
                    .addGroup(jpAgregarMateriaLayout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlFormulario)
                            .addGroup(jpAgregarMateriaLayout.createSequentialGroup()
                                .addComponent(jbGuardar)
                                .addGap(30, 30, 30)
                                .addComponent(jbNuevo)))
                        .addGap(39, 39, 39)
                        .addComponent(jbsalir)))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jpAgregarMateriaLayout.setVerticalGroup(
            jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpAgregarMateriaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlFormulario)
                .addGap(44, 44, 44)
                .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCodigo)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlNombre)
                    .addComponent(jtfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlAño)
                    .addComponent(jtfAño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jpAgregarMateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardar)
                    .addComponent(jbNuevo)
                    .addComponent(jbsalir))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAgregarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpAgregarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbNuevo;
    private javax.swing.JButton jbsalir;
    private javax.swing.JLabel jlAño;
    private javax.swing.JLabel jlCodigo;
    private javax.swing.JLabel jlFormulario;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JPanel jpAgregarMateria;
    private javax.swing.JTextField jtfAño;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfNombre;
    // End of variables declaration//GEN-END:variables
}
