/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

/**
 *
 * @author alybe
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jAlumno = new javax.swing.JMenu();
        jAlumno1 = new javax.swing.JMenuItem();
        jMateria = new javax.swing.JMenu();
        jMateria1 = new javax.swing.JMenuItem();
        jRegistro = new javax.swing.JMenu();
        jRegistro1 = new javax.swing.JMenuItem();
        jSalir = new javax.swing.JMenu();
        JSalir1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout EscritorioLayout = new javax.swing.GroupLayout(Escritorio);
        Escritorio.setLayout(EscritorioLayout);
        EscritorioLayout.setHorizontalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 593, Short.MAX_VALUE)
        );
        EscritorioLayout.setVerticalGroup(
            EscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jAlumno.setText("Alumno");

        jAlumno1.setText("Agregar Alumno");
        jAlumno1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jAlumno1ActionPerformed(evt);
            }
        });
        jAlumno.add(jAlumno1);

        jMenuBar.add(jAlumno);

        jMateria.setText("Materia");

        jMateria1.setText("Agregar Materia");
        jMateria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMateria1ActionPerformed(evt);
            }
        });
        jMateria.add(jMateria1);

        jMenuBar.add(jMateria);

        jRegistro.setText("Registro");

        jRegistro1.setText("Agregar Registro");
        jRegistro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegistro1ActionPerformed(evt);
            }
        });
        jRegistro.add(jRegistro1);

        jMenuBar.add(jRegistro);

        jSalir.setText("Salir");

        JSalir1.setText("Salir");
        JSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSalir1ActionPerformed(evt);
            }
        });
        jSalir.add(JSalir1);

        jMenuBar.add(jSalir);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jAlumno1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAlumno1ActionPerformed
       AgregarAlumno alumnos = new AgregarAlumno(); 
    Escritorio.add(alumnos);
    alumnos.setVisible(true);

    }//GEN-LAST:event_jAlumno1ActionPerformed

    private void jMateria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMateria1ActionPerformed
        // TODO add your handling code here:
         AgregarMateria materia = new AgregarMateria(); 
    Escritorio.add(materia);
    materia.setVisible(true);
    }//GEN-LAST:event_jMateria1ActionPerformed

    private void JSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSalir1ActionPerformed
        // TODO add your handling code here:
         System.exit(0);   
    }//GEN-LAST:event_JSalir1ActionPerformed

    private void jRegistro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegistro1ActionPerformed
        // TODO add your handling code here:
         AgregarRegistro registro = new AgregarRegistro(); 
    Escritorio.add(registro);
    registro.setVisible(true);
 
    }//GEN-LAST:event_jRegistro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem JSalir1;
    private javax.swing.JMenu jAlumno;
    private javax.swing.JMenuItem jAlumno1;
    private javax.swing.JMenu jMateria;
    private javax.swing.JMenuItem jMateria1;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jRegistro;
    private javax.swing.JMenuItem jRegistro1;
    private javax.swing.JMenu jSalir;
    // End of variables declaration//GEN-END:variables
}
